### ISSUE TITLE
Error when trying to create the tempfile

### ISSUE THREAD

**Issue by ljmasague** [dimiro1/lambda-wkhtmltopdf#1]
Hello, 
Thanks for the library, I'm trying to use it but i'm getting this error:
Error: ENOENT: no such file or directory, open '/tmp/pdffilename.pdf'.
Any ideas on what am i doing wrong?
Thanks

**Comment by dimiro1** [comment]
Are you using Windows?

**Comment by ljmasague** [comment]
Yes.

**Comment by dimiro1** [comment]
This project only works in Amazon Lambda[1] running Linux.

[1] https://aws.amazon.com/lambda/

**Comment by ljmasague** [comment]
Ok. I'll try compile with a Linux virtual machine. Thank you very much

El 16 may. 2017 10:35 p. m., "Claudemiro" <notifications@github.com>
escribió:

This project only works in Amazon Lambda[1] running Linux.

[1] https://aws.amazon.com/lambda/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dimiro1/lambda-wkhtmltopdf/issues/1#issuecomment-301907509>,
or mute the thread

**Comment by dimiro1** [comment]
Can you explain how are you using this library?
